#!/bin/bash
#========================================================
# Script Name: projectmenu
# By: jay kaplan
# Date: 12/12/2014
# Purpose: A menu for the Semester Project
# Command Line: projectmenu
#========================================================
trap "rm ./f 2> /dev/null; exit" 0 1 3
userfile=~/project/datafile
loop=y
while test $loop = "y"
do
clear
tput cup 3 12; echo "Menu"
tput cup 4 12; echo "========================"
tput cup 6 9; echo "(p, P) Print users info"
tput cup 7 9; echo "(a, A) Add new user"
tput cup 8 9; echo "(s, S) Search user"
tput cup 9 9; echo "(d, D) Delete user"
tput cup 10 9; echo "(x, X) Exit"
tput cup 12 9; echo "Enter your choice:"
tput cup 12 29;
read choice || continue
  case $choice in
     [Pp]) ./printuser ;;
     [Aa]) ./adduser ;;
     [Ss]) ./searchuser ;;
     [Dd]) ./deleteuser ;;
     [Xx]) clear ; exit ;;
     *) tput cup 15 5; echo "Invalid Code"; read choice ;;
  esac
done
